"""Add admin models

Revision ID: 8aceebd1761e
Revises: 0007_add_tribunal_tables
Create Date: 2026-08-29 01:43:49.010377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aceebd1761e'
down_revision: Union[str, Sequence[str], None] = '0007_add_tribunal_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_proposal_id'), 'audit_events', ['proposal_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'REVISION_REQUESTED', name='reviewdecisionenum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_proposal_id'), 'review_decisions', ['proposal_id'], unique=False)
    op.alter_column('human_reviews', 'action',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('APPROVE', 'REJECT', 'REQUEST_MORE_INFO', name='reviewaction'),
               existing_nullable=False)
    op.alter_column('llm_runs', 'prompt_version',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('llm_runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('tribunal_sessions', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'EVIDENCE_RETRIEVAL', 'AI_ANALYSIS', 'ADVOCATE_RUNNING', 'CRITIC_RUNNING', 'JUDGE_RUNNING', 'COMPLETED', 'FAILED', name='tribunalstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('tribunal_sessions', 'decision',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('APPROVE', 'REJECT', 'REVIEW', name='tribunaldecision'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tribunal_sessions', 'decision',
               existing_type=sa.Enum('APPROVE', 'REJECT', 'REVIEW', name='tribunaldecision'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tribunal_sessions', 'status',
               existing_type=sa.Enum('PENDING', 'EVIDENCE_RETRIEVAL', 'AI_ANALYSIS', 'ADVOCATE_RUNNING', 'CRITIC_RUNNING', 'JUDGE_RUNNING', 'COMPLETED', 'FAILED', name='tribunalstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('llm_runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('llm_runs', 'prompt_version',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'1.0'::character varying"))
    op.alter_column('human_reviews', 'action',
               existing_type=sa.Enum('APPROVE', 'REJECT', 'REQUEST_MORE_INFO', name='reviewaction'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_review_decisions_proposal_id'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_audit_events_proposal_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
